### ISSUE TITLE
Type error after update to 6.1.0  

### ISSUE THREAD

**Issue by AnimusXCASH** [StellarCN/py-stellar-base#562]
Hi, 

I just updated to latest version and when I want to run the main.py script a Type error is returned. Before update everything was working normally. Is this the package related error or?

```File "/home/ubuntu/Hot_wallet_monitor_Stellar/walletMonitor/lib/python3.8/site-packages/stellar_sdk/server.py", line 51, in __init__
    client = RequestsClient()
  File "/home/ubuntu/Hot_wallet_monitor_Stellar/walletMonitor/lib/python3.8/site-packages/typeguard/__init__.py", line 1032, in wrapper
    retval = func(*args, **kwargs)
  File "/home/ubuntu/Hot_wallet_monitor_Stellar/walletMonitor/lib/python3.8/site-packages/stellar_sdk/client/requests_client.py", line 68, in __init__
    retry = Retry(
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'```

Any ideas on why this might be happening?

thank you for your time and answer. 

Animus

**Comment by overcat** [comment]
Do you mind posting the output of `pip freeze` here? Thanks.

**Comment by overcat** [comment]
I think executing `pip install -U urllib3` should solve this problem, but before executing this command, please run `pip freeze` to get the current urllib3 version, which will help us solve this problem, thank you.

**Comment by overcat** [comment]
[6.1.1](https://github.com/StellarCN/py-stellar-base/releases/tag/6.1.1) released, maybe it can solve this problem, whether it works well or not, please give me a feedback, thank you.

**Comment by AnimusXCASH** [comment]
aiohttp==3.6.2
aiohttp-sse-cl
appdirs==1.4.3
APScheduler==3
astroid==2.3.3
async-timeout=
attrs==19.3.0 
CacheControl==
certifi==2019.
cffi==1.14.3  
chardet==3.0.4
colorama==0.4.
contextlib2==0
crc16==0.1.1  
cryptography==
Deprecated==1.
discord-compon
discord.py==1.
distlib==0.3.0
distro==1.4.0 
gitdb==4.0.5  
html5lib==1.0.
idna==2.8     
ipaddr==2.2.0 
lazy-object-pr
lockfile==0.12
mnemonic==0.19
motor==2.3.0  
msgpack==0.6.2
multidict==4.7
oauthlib==3.1.
packaging==20.
pep517==0.8.2 
Pillow==8.3.1 
progress==1.5 
pycoingecko==1
pycparser==2.2
pycrypto==2.6.
PyJWT==1.7.1  
pymongo==3.11.
PyNaCl==1.3.0 
pyparsing==2.4
pypng==0.0.20 
PyQRCode==1.2.
PySocks==1.7.1
pytoml==0.1.21
pytz==2019.3  
qrcode==7.2   
requests==2.22
requests-oauth
retrying==1.3.
six==1.14.0   
smmap==3.0.4  
stellar-base-s
stellar-sdk==2
toml==0.10.1  
tweepy==3.9.0 
tzlocal==2.0.0
urllib3==1.25.
webencodings==
wrapt==1.11.2 
yarl==1.4.2

**Comment by overcat** [comment]
@AnimusXCASH Thanks! Upgrading to 6.1.1 should solve your problem.

**Comment by AnimusXCASH** [comment]
@overcat Yes indeed, it solved the issue. Appreciate and thanks for all the work :) 

Animus
Crypto Link
