### ISSUE TITLE
Failure to instantiate a Server object in Python 3.8.5

### ISSUE THREAD

**Issue by tomerweller** [StellarCN/py-stellar-base#461]
**Describe the bug**
Failure to instantiate a `Server` object in Python3.8.5 (the exact same code works in python 3.9.3)

Relevant part of the stack trace:
```
...
  File "/<redacted>/.local/lib/python3.8/site-packages/stellar_sdk/server.py", line 76, in __init__
    client = RequestsClient()
  File "/<redacted>/.local/lib/python3.8/site-packages/stellar_sdk/client/requests_client.py", line 66, in __init__
    retry = Retry(
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'
```

**What version of dependencies are you using?**
stellar-sdk==3.2.0

**To Reproduce**
Instantiate a `Server` object

**Comment by overcat** [comment]
I think it may only be caused by dependency conflicts, Python Stellar SDK requires **urllib3 >= 1.26.0**. Can you provide the version of urllib3 you are using? You can get its version number through `pip freeze | grep urllib3`.

Perhaps you can temporarily solve this problem by upgrading urllib3.
`pip install urllib3==1.26.4`

-----
Here is some additional information.

In urllib3 [1.26.0](https://github.com/urllib3/urllib3/releases/tag/1.26.0), `method_whitelist` was replaced by `allowed_methods`, and `method_whitelist` will be removed in urllib3 2.0.0, so you see this error.

Here are the relevant code changes. #444

**Comment by overcat** [comment]
This issue is closed due to not being active. Please feel free to reopen it again if you still encounter this issue with the [latest version](https://pypi.org/project/stellar-sdk/).

Thank you!
